name: 01-Building-Blocks
on:
  - push
  - workflow_dispatch
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "Hello World !"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
    