name: 02-workflow-events
on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run:  |
          echo "Event Name : ${{github.event_name}}"
