name: 06-using-context
run-name: Contexts | Debug-${{inputs.debug}}
on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: Kindly provide the value
env:
  MY_WORKFLOW_NAME: ${{ var.MY_VAR || "Default Workflow Name"}}
jobs:
  display-information:
    runs-on: ubuntu-latest
    steps:
      - name: Display Event Information
        if: ${{inputs.debug && github.ref == 'refs/heads/main'}}
        run:  |
          echo "Event Name : ${{github.event_name}}"
          echo "Ref:  ${{github.ref}}"
          echo  "SHA: ${{github.sha}}"

      - name: Display Variable Information
        run:  |
          echo "My Variable:  ${{vars.MY_VARIABLE}}"
          echo "Environment Variable: ${{env.MY_WORKFLOW_NAME}}"