name: inputs-demo
on:
  push:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean #either boolean,choice,number,environment
        description: Whether needs to dry-run
        default: false
      target:
        type: environment
        description: Decide which environment needs to deploy
        required: true
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        description: Choose which tag needs to select
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{steps.build.outputs.status}}
    steps:
      - name: Build
        id: build
        run: |
          echo "Building from tag ${{inputs.tag}}"
          echo "status=success" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run }}
    environment: ${{inputs.target}}
    needs: build
    steps:
      - name: Deploy
        if: ${{needs.build.outputs.build-status == "success"}}
        run: echo "Deploying to ${{inputs.target}}"